project_id             = ""
cluster_name           = "demo"
region                 = "us-central1"
network                = "demo-vpc-network"
subnetwork             = "demo-subnet-1"
ip_range_pods_name     = "demo-ip-range-pods"
ip_range_services_name = "demo-ip-range-services"
